apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../base

patchesJson6902:
  - target:
      group: logging.openshift.io
      version: v1
      kind: ClusterLogging
      name: instance
      namespace: openshift-logging
    path: patch-cluster-logging.yaml