apiVersion: machine.openshift.io/v1beta1
kind: MachineSet
metadata:
  creationTimestamp: null
  labels:
    machine.openshift.io/cluster-api-cluster: asd123qwe456 
  name: asd123qwe456-storage 
  namespace: openshift-machine-api
spec:
  replicas: 1
  selector:
    matchLabels:
      machine.openshift.io/cluster-api-cluster: asd123qwe456 
      machine.openshift.io/cluster-api-machineset: asd123qwe456-storage 
  template:
    metadata:
      creationTimestamp: null
      labels:
        machine.openshift.io/cluster-api-cluster: asd123qwe456 
        machine.openshift.io/cluster-api-machine-role: storage 
        machine.openshift.io/cluster-api-machine-type: storage 
        machine.openshift.io/cluster-api-machineset: asd123qwe456-storage 
    spec:
      metadata:
        creationTimestamp: null
        labels:
          node-role.kubernetes.io/storage: ""
          node-role.kubernetes.io/worker: ""
          node-role.kubernetes.io/infra: ""
          cluster.ocs.openshift.io/openshift-storage: ""
      taints:
      - effect: NoSchedule
        key: node.ocs.openshift.io/storage
        value: "true"
      providerSpec:
        value:
          apiVersion: vsphereprovider.openshift.io/v1beta1
          credentialsSecret:
            name: vsphere-cloud-credentials
          diskGiB: 120
          kind: VSphereMachineProviderSpec
          memoryMiB: 8192
          metadata:
            creationTimestamp: null
          network:
            devices:
            - networkName: "<vm_network_name>" 
          numCPUs: 4
          numCoresPerSocket: 1
          snapshot: ""
          template: <vm_template_name> 
          userDataSecret:
            name: worker-user-data
          workspace:
            datacenter: <vcenter_datacenter_name> 
            datastore: <vcenter_datastore_name> 
            folder: <vcenter_vm_folder_path> 
            resourcepool: <vsphere_resource_pool> 
            server: <vcenter_server_ip> 